-- SWH DB schema upgrade
-- from_version: 89
-- to_version: 90
-- description: indexer: Add content_ctags

insert into dbversion(version, release, description)
      values(90, now(), 'Work In Progress');

comment on type content_status is 'Content visibility';
comment on type entity_type is 'Entity types';
comment on type revision_type is 'Possible revision types';
comment on type object_type is 'Data object types stored in data model';
comment on type languages is 'Languages recognized by language indexer';
comment on type ctags_languages is 'Languages recognized by ctags indexer';

create table license(
  id serial primary key,
  name bytea not null
);

comment on table license is 'Possible license recognized by license indexer';
comment on column license.id is 'License identifier';
comment on column license.name is 'License name';

create unique index on license(name);

create table content_license (
  id sha1 primary key references content(sha1) not null,
  licenses bigint[] -- reference license(id)
);

comment on table content_license is 'license associated to a raw content';
comment on column content_license.id is 'Raw content identifier';
comment on column content_license.licenses is 'Raw content licenses';

insert into license (name)
values
  ('3DFX'),
  ('3DFX-PL'),
  ('AAL'),
  ('ACAA'),
  ('ACDL'),
  ('ACE'),
  ('Adaptec-GPL'),
  ('Adaptec(RESTRICTED)'),
  ('Adobe-AFM'),
  ('Adobe-EULA'),
  ('AFL'),
  ('AFL-1.0'),
  ('AFL-1.1'),
  ('AFL-1.2'),
  ('AFL-2.0'),
  ('AFL-2.1'),
  ('AFL-3.0'),
  ('AFPL-Ghostscript'),
  ('AgainstDRM'),
  ('AGE-Logic'),
  ('Agere-EULA'),
  ('AGFA-EULA'),
  ('AGFA(RESTRICTED)'),
  ('AGPL'),
  ('AGPL-1.0'),
  ('AGPL-1.0+'),
  ('AGPL-3.0'),
  ('AGPL-3.0+'),
  ('Aladdin'),
  ('Alfresco'),
  ('Alfresco/FLOSS'),
  ('Algorithmics'),
  ('AMD'),
  ('AMD-EULA'),
  ('ANTLR-PD'),
  ('AOL-EULA'),
  ('Apache'),
  ('Apache-1.0'),
  ('Apache-1.1'),
  ('Apache-2.0'),
  ('Apache-style'),
  ('Apache-v1.0'),
  ('APL'),
  ('APL-1.0'),
  ('Apple(FontForge)'),
  ('Apple(Sample)'),
  ('APSL'),
  ('APSL-1.0'),
  ('APSL-1.1'),
  ('APSL-1.2'),
  ('APSL-2.0'),
  ('APSL-style'),
  ('Aptana'),
  ('Aptana-1.0'),
  ('ARJ'),
  ('Arphic-Font-PL'),
  ('Arphic-style'),
  ('Artifex'),
  ('Artistic-1.0-cl8'),
  ('Artistic-1.0-Perl'),
  ('Ascender-EULA'),
  ('ATI-EULA'),
  ('ATMEL-FW'),
  ('ATT(Non-commercial)'),
  ('ATT-Source'),
  ('ATT-Source-1.0'),
  ('ATT-Source-1.2d'),
  ('Baekmuk-Font'),
  ('Baekmuk(Hwan)'),
  ('BancTec'),
  ('Beerware'),
  ('Bellcore'),
  ('Bellcore-style'),
  ('BH-Font'),
  ('BH-Font-style'),
  ('BISON'),
  ('BitTorrent'),
  ('BitTorrent-1.0'),
  ('BitTorrent-1.1'),
  ('BIZNET'),
  ('BIZNET-style'),
  ('BrainStorm-EULA'),
  ('Broadcom-EULA'),
  ('BSD-2-Clause'),
  ('BSD-2-Clause-FreeBSD'),
  ('BSD-2-Clause-NetBSD'),
  ('BSD-3-Clause'),
  ('BSD-3-Clause-Clear'),
  ('BSD-3-Clause-Severability'),
  ('BSD-4-Clause'),
  ('BSD-4-Clause-UC'),
  ('BSL-1.0'),
  ('BSL-style'),
  ('CA'),
  ('Cadence'),
  ('CATOSL'),
  ('CATOSL-1.1'),
  ('CC0-1.0'),
  ('CC-BY'),
  ('CC-BY-1.0'),
  ('CC-BY-2.0'),
  ('CC-BY-2.5'),
  ('CC-BY-3.0'),
  ('CC-BY-4.0'),
  ('CC-BY-NC-1.0'),
  ('CC-BY-NC-2.0'),
  ('CC-BY-NC-2.5'),
  ('CC-BY-NC-3.0'),
  ('CC-BY-NC-4.0'),
  ('CC-BY-NC-ND-1.0'),
  ('CC-BY-NC-ND-2.0'),
  ('CC-BY-NC-ND-2.5'),
  ('CC-BY-NC-ND-3.0'),
  ('CC-BY-NC-ND-4.0'),
  ('CC-BY-NC-SA-1.0'),
  ('CC-BY-NC-SA-2.0'),
  ('CC-BY-NC-SA-2.5'),
  ('CC-BY-NC-SA-3.0'),
  ('CC-BY-NC-SA-4.0'),
  ('CC-BY-ND-1.0'),
  ('CC-BY-ND-2.0'),
  ('CC-BY-ND-2.5'),
  ('CC-BY-ND-3.0'),
  ('CC-BY-ND-4.0'),
  ('CC-BY-SA'),
  ('CC-BY-SA-1.0'),
  ('CC-BY-SA-2.0'),
  ('CC-BY-SA-2.5'),
  ('CC-BY-SA-3.0'),
  ('CC-BY-SA-4.0'),
  ('CC-LGPL'),
  ('CC-LGPL-2.1'),
  ('CCLRC'),
  ('CCPL'),
  ('CDDL'),
  ('CDDL-1.0'),
  ('CDDL-1.1'),
  ('CECILL'),
  ('CECILL-2.0'),
  ('CECILL-B'),
  ('CECILL-C'),
  ('CECILL(dual)'),
  ('Cisco'),
  ('Cisco-style'),
  ('Citrix'),
  ('ClArtistic'),
  ('ClearSilver'),
  ('CMake'),
  ('CMU-style'),
  ('CNRI-Python'),
  ('CNRI-Python-GPL-Compatible'),
  ('Combined_OpenSSL+SSLeay'),
  ('CompuServe'),
  ('Comtrol'),
  ('Condor-1.0'),
  ('Condor-1.1'),
  ('CopyLeft[1]'),
  ('CopyLeft[2]'),
  ('CPL'),
  ('CPL-0.5'),
  ('CPL-1.0'),
  ('CPOL'),
  ('CPOL-1.02'),
  ('Cryptogams'),
  ('CUA-OPL-1.0'),
  ('CUPS'),
  ('CUPS-EULA'),
  ('Cylink-ISC'),
  ('Cypress-FW'),
  ('DARPA'),
  ('DARPA-Cougaar'),
  ('Debian-social-DFSG'),
  ('Debian-SPI'),
  ('Debian-SPI-style'),
  ('D-FSL-1.0'),
  ('DMTF'),
  ('DOCBOOK'),
  ('DOCBOOK-style'),
  ('DPTC'),
  ('DSCT'),
  ('DSL'),
  ('Dyade'),
  ('EBT-style'),
  ('ECL-1.0'),
  ('ECL-2.0'),
  ('eCos-2.0'),
  ('EFL'),
  ('EFL-1.0'),
  ('EFL-2.0'),
  ('eGenix'),
  ('Empty-file-no-data!'),
  ('Entessa'),
  ('Epinions'),
  ('Epson-EULA'),
  ('Epson-PL'),
  ('ErlPL-1.1'),
  ('EUDatagrid'),
  ('EUPL-1.0'),
  ('EUPL-1.1'),
  ('FaCE'),
  ('Fair'),
  ('Fair-style'),
  ('FAL-1.0'),
  ('FAL-1.3'),
  ('FedoraCLA'),
  ('Flash2xml-1.0'),
  ('Flora'),
  ('Flora-1.0'),
  ('Flora-1.1'),
  ('Frameworx'),
  ('Frameworx-1.0'),
  ('FreeBSD-Doc'),
  ('Free-PL'),
  ('Free-SW'),
  ('FTL'),
  ('FTL-style'),
  ('Fujitsu'),
  ('Garmin-EULA'),
  ('Genivia(Commercial)'),
  ('GFDL'),
  ('GFDL-1.1'),
  ('GFDL-1.1+'),
  ('GFDL-1.2'),
  ('GFDL-1.2+'),
  ('GFDL-1.3'),
  ('GFDL-v1.2'),
  ('Ghostscript-GPL-1.1'),
  ('Giftware'),
  ('GNU-copyleft'),
  ('GNU-Ghostscript'),
  ('GNU-javamail-exception'),
  ('GNU-Manpages'),
  ('Google-BSD'),
  ('Govt-restrict'),
  ('GPL'),
  ('GPL-1.0'),
  ('GPL-1.0+'),
  ('GPL-2.0'),
  ('GPL-2.0+'),
  ('GPL-2.0:3.0'),
  ('GPL-2.0+:3.0'),
  ('GPL-2.0+KDEupgradeClause'),
  ('GPL-2.0-with-autoconf-exception'),
  ('GPL-2.0-with-bison-exception'),
  ('GPL-2.0+-with-bison-exception'),
  ('GPL-2.0-with-classpath-exception'),
  ('GPL-2.0+-with-classpath-exception'),
  ('GPL-2.0-with-font-exception'),
  ('GPL-2.0-with-GCC-exception'),
  ('GPL-2.1[sic]'),
  ('GPL-2.1+[sic]'),
  ('GPL-3?'),
  ('GPL-3.0'),
  ('GPL-3.0+'),
  ('GPL-3.0-with-autoconf-exception'),
  ('GPL-3.0-with-GCC-exception'),
  ('GPL-3.0+-with-GCC-exception'),
  ('GPL-Meta'),
  ('GPL-or-LGPL'),
  ('GPL(rms)'),
  ('GPL-with-autoconf-exception'),
  ('gSOAP'),
  ('gSOAP-1.3b'),
  ('H2'),
  ('H2-1.0'),
  ('Hacktivismo'),
  ('Hauppauge'),
  ('Helix/RealNetworks-EULA'),
  ('HPND'),
  ('IBM-Courier'),
  ('IBM-JCL'),
  ('IBM-pibs'),
  ('IBM-reciprocal'),
  ('ID-EULA'),
  ('IDPL'),
  ('IDPL-1.0'),
  ('IEEE-Doc'),
  ('IETF'),
  ('IETF-style'),
  ('IJG'),
  ('ImageMagick'),
  ('ImageMagick(Apache)'),
  ('ImageMagick-style'),
  ('Imlib2'),
  ('InfoSeek'),
  ('info-zip'),
  ('InnerNet'),
  ('InnerNet-2.00'),
  ('InnerNet-style'),
  ('Intel-EULA'),
  ('Intel(RESTRICTED)'),
  ('Intel-WLAN'),
  ('Interbase-1.0'),
  ('Interbase-PL'),
  ('Interlink-EULA'),
  ('Intranet-only'),
  ('IOS'),
  ('IoSoft(COMMERCIAL)'),
  ('IPA'),
  ('IPA-Font-EULA'),
  ('IPL'),
  ('IPL-1.0'),
  ('IPL-2.0'),
  ('IPTC'),
  ('IronDoc'),
  ('ISC'),
  ('Jabber'),
  ('Java-WSDL4J'),
  ('Java-WSDL-Policy'),
  ('Java-WSDL-Schema'),
  ('Java-WSDL-Spec'),
  ('JISP'),
  ('JPNIC'),
  ('JSON'),
  ('KDE'),
  ('Keyspan-FW'),
  ('KnowledgeTree-1.1'),
  ('Knuth-style'),
  ('Lachman-Proprietary'),
  ('Larabie-EULA'),
  ('LDP-1A'),
  ('LDP-2.0'),
  ('Legato'),
  ('Leptonica'),
  ('LGPL'),
  ('LGPL-1.0'),
  ('LGPL-1.0+'),
  ('LGPL-2.0'),
  ('LGPL-2.0+'),
  ('LGPL-2.1'),
  ('LGPL-2.1+'),
  ('LGPL-2.1+-KDE-exception'),
  ('LGPL-3?'),
  ('LGPL-3.0'),
  ('LGPL-3.0+'),
  ('LIBGCJ'),
  ('Libpng'),
  ('Link-exception'),
  ('LinuxDoc'),
  ('Linux-HOWTO'),
  ('Logica-OSL-1.0'),
  ('LPL-1.0'),
  ('LPL-1.02'),
  ('LPPL'),
  ('LPPL-1.0'),
  ('LPPL-1.0+'),
  ('LPPL-1.1'),
  ('LPPL-1.1+'),
  ('LPPL-1.2'),
  ('LPPL-1.2+'),
  ('LPPL-1.3'),
  ('LPPL-1.3+'),
  ('LPPL-1.3a'),
  ('LPPL-1.3a+'),
  ('LPPL-1.3b'),
  ('LPPL-1.3b+'),
  ('LPPL-1.3c'),
  ('LPPL-1.3c+'),
  ('MacroMedia-RPSL'),
  ('Macrovision'),
  ('Macrovision-EULA'),
  ('Majordomo'),
  ('Majordomo-1.1'),
  ('Mandriva'),
  ('Mellanox'),
  ('MetroLink'),
  ('MetroLink-nonfree'),
  ('Mibble'),
  ('Mibble-2.8'),
  ('Microsoft'),
  ('Migemo'),
  ('MindTerm'),
  ('MirOS'),
  ('MITEM'),
  ('MitreCVW-style'),
  ('Motosoto'),
  ('MPEG3-decoder'),
  ('MPL'),
  ('MPL-1.0'),
  ('MPL-1.1'),
  ('MPL-1.1+'),
  ('MPL-1.1-style'),
  ('MPL-2.0'),
  ('MPL-2.0-no-copyleft-exception'),
  ('MPL-EULA-1.1'),
  ('MPL-EULA-2.0'),
  ('MPL-EULA-3.0'),
  ('MPL-style'),
  ('M-Plus-Project'),
  ('MRL'),
  ('MS-indemnity'),
  ('MS-LPL'),
  ('MS-LRL'),
  ('Multics'),
  ('MX4J'),
  ('MX4J-1.0'),
  ('MySQL-0.3'),
  ('MySQL/FLOSS'),
  ('MySQL-style'),
  ('NASA'),
  ('NASA-1.3'),
  ('Naumen'),
  ('NBPL-1.0'),
  ('nCipher'),
  ('NCSA'),
  ('NESSUS-EULA'),
  ('NGPL'),
  ('Nokia'),
  ('No_license_found'),
  ('non-ATT-BSD'),
  ('None'),
  ('NOSL-1.0'),
  ('Not-for-sale!'),
  ('Not-Free!'),
  ('Not-Internet'),
  ('Not-OpenSource!'),
  ('NOT-Open-Source!'),
  ('NOT-public-domain'),
  ('Novell'),
  ('Novell-EULA'),
  ('NPL'),
  ('NPL-1.0'),
  ('NPL-1.1'),
  ('NPL-1.1+'),
  ('NPL-EULA'),
  ('NPOSL-3.0'),
  ('NRL'),
  ('NTP'),
  ('OASIS'),
  ('OCL'),
  ('OCL-1.0'),
  ('OCLC'),
  ('OCLC-1.0'),
  ('OCLC-2.0'),
  ('OCL-style'),
  ('ODbL-1.0'),
  ('ODL'),
  ('OFL-1.0'),
  ('OFL-1.1'),
  ('OGTSL'),
  ('OLDAP'),
  ('OLDAP-1.1'),
  ('OLDAP-1.2'),
  ('OLDAP-1.3'),
  ('OLDAP-1.4'),
  ('OLDAP-2.0'),
  ('OLDAP-2.0.1'),
  ('OLDAP-2.1'),
  ('OLDAP-2.2'),
  ('OLDAP-2.2.1'),
  ('OLDAP-2.2.2'),
  ('OLDAP-2.3'),
  ('OLDAP-2.4'),
  ('OLDAP-2.5'),
  ('OLDAP-2.6'),
  ('OLDAP-2.7'),
  ('OLDAP-2.8'),
  ('OLDAP-style'),
  ('OMF'),
  ('Ontopia'),
  ('OpenCASCADE-PL'),
  ('OpenGroup'),
  ('OpenGroup-Proprietary'),
  ('OpenMarket'),
  ('Open-PL'),
  ('Open-PL-0.4'),
  ('Open-PL-1.0'),
  ('Open-PL-style'),
  ('OPL-1.0'),
  ('Oracle-Berkeley-DB'),
  ('O''Reilly'),
  ('O''Reilly-style'),
  ('OSD'),
  ('OSL'),
  ('OSL-1.0'),
  ('OSL-1.1'),
  ('OSL-2.0'),
  ('OSL-2.1'),
  ('OSL-3.0'),
  ('Paradigm'),
  ('Patent-ref'),
  ('PDDL-1.0'),
  ('Phorum'),
  ('PHP-3.0'),
  ('PHP-style'),
  ('Piriform'),
  ('Pixware-EULA'),
  ('Polyserve-CONFIDENTIAL'),
  ('Postfix'),
  ('PostgreSQL'),
  ('Powder-Proprietary'),
  ('Princeton'),
  ('Princeton-style'),
  ('Proprietary!'),
  ('Public-domain'),
  ('Public-domain(C)'),
  ('Public-domain-ref'),
  ('Public-Use'),
  ('Public-Use-1.0'),
  ('Python'),
  ('Python-2.0'),
  ('Python-2.0.1'),
  ('Python-2.0.2'),
  ('Python-2.1.1'),
  ('Python-2.1.3'),
  ('Python-2.2'),
  ('Python-2.2.3'),
  ('Python-2.2.7'),
  ('Python-2.3'),
  ('Python-2.3.7'),
  ('Python-2.4.4'),
  ('Python-style'),
  ('Qmail'),
  ('QPL'),
  ('QPL-1.0'),
  ('QT(Commercial)'),
  ('QuarterDeck'),
  ('Quest-EULA'),
  ('RCSL'),
  ('RCSL-1.0'),
  ('RCSL-2.0'),
  ('RCSL-3.0'),
  ('RealNetworks-EULA'),
  ('RealNetworks-Unknown'),
  ('RedHat-EULA'),
  ('Redland'),
  ('Restricted-rights'),
  ('RHeCos-1.1'),
  ('Riverbank-EULA'),
  ('RPL-1.5'),
  ('RPSL'),
  ('RPSL-1.0'),
  ('RPSL-2.0'),
  ('RPSL-3.0'),
  ('RSCPL'),
  ('Ruby'),
  ('SAX-PD'),
  ('SciTech'),
  ('SCO(commercial)'),
  ('SCSL'),
  ('SCSL-2.3'),
  ('SCSL-3.0'),
  ('SCSL-TSA'),
  ('SCSL-TSA-1.0'),
  ('See-doc(OTHER)'),
  ('See-file'),
  ('See-file(COPYING)'),
  ('See-file(LICENSE)'),
  ('See-file(README)'),
  ('See-URL'),
  ('Sendmail'),
  ('SGI'),
  ('SGI-B-1.0'),
  ('SGI-B-1.1'),
  ('SGI-B-2.0'),
  ('SGI-Freeware'),
  ('SGI_GLX'),
  ('SGI-Proprietary'),
  ('SGI-style'),
  ('SGML'),
  ('SimPL-2.0'),
  ('SISSL'),
  ('SISSL-1.1'),
  ('SISSL-1.2'),
  ('Skype-EULA'),
  ('Sleepycat(Non-commercial)'),
  ('SMLNJ'),
  ('SNIA'),
  ('SNIA-1.0'),
  ('SNIA-1.1'),
  ('SpikeSource'),
  ('SPL'),
  ('SPL-1.0'),
  ('Stanford'),
  ('Stanford-style'),
  ('SugarCRM-1.1.3'),
  ('Sun-BCLA-1.5.0'),
  ('Sun-EULA'),
  ('Sun-IP'),
  ('Sun-Java'),
  ('Sun(Non-commercial)'),
  ('SunPro'),
  ('Sun(RESTRICTED)'),
  ('Sun-RPC'),
  ('Sun-SCA'),
  ('Sun(tm)'),
  ('SW-Research'),
  ('Tapjoy'),
  ('Tektronix'),
  ('Tektronix-style'),
  ('Trademark-ref'),
  ('Trident-EULA'),
  ('Trolltech'),
  ('U-BC'),
  ('U-Cambridge'),
  ('U-Cambridge-style'),
  ('UCAR'),
  ('UCAR-style'),
  ('U-Chicago'),
  ('U-Columbia'),
  ('UCWare-EULA'),
  ('U-Del'),
  ('U-Del-style'),
  ('U-Monash'),
  ('UnclassifiedLicense'),
  ('Unidex'),
  ('UnitedLinux-EULA'),
  ('Unlicense'),
  ('unRAR restriction'),
  ('URA(gov''t)'),
  ('USC'),
  ('USC(Non-commercial)'),
  ('USC-style'),
  ('US-Export-restrict'),
  ('U-Utah'),
  ('U-Wash(Free-Fork)'),
  ('VIM'),
  ('Vixie'),
  ('Vixie-license'),
  ('VMware-EULA'),
  ('VSL-1.0'),
  ('Wash-U-style'),
  ('Watcom'),
  ('Watcom-1.0'),
  ('WebM'),
  ('Wintertree'),
  ('WordNet-3.0'),
  ('WTFPL'),
  ('WTI(Not-free)'),
  ('WXwindows'),
  ('X11'),
  ('Xerox'),
  ('Xerox-style'),
  ('XFree86'),
  ('XFree86-1.0'),
  ('XFree86-1.1'),
  ('Ximian'),
  ('Ximian-1.0'),
  ('XMLDB-1.0'),
  ('Xnet'),
  ('XOPEN-EULA'),
  ('X/Open-style'),
  ('Yahoo-EULA'),
  ('YaST(SuSE)'),
  ('YPL'),
  ('YPL-1.0'),
  ('YPL-1.1'),
  ('Zend-2.0'),
  ('Zeus'),
  ('Zimbra'),
  ('Zimbra-1.2'),
  ('Zimbra-1.3'),
  ('Zlib'),
  ('ZoneAlarm-EULA'),
  ('ZPL-1.0'),
  ('ZPL-1.1'),
  ('ZPL-2.0'),
  ('ZPL-2.1'),
  ('Zveno');

-- create a temporary table for content_license tmp_content_license,
create or replace function swh_mktemp_content_license()
    returns void
    language sql
as $$
  create temporary table tmp_content_license (
    id       sha1,
    licenses bytea[]
  ) on commit drop;
$$;

comment on function swh_mktemp_content_license() is 'Helper table to add content license';

-- check which entries of tmp_bytea are missing from content_license
--
-- operates in bulk: 0. swh_mktemp_bytea(), 1. COPY to tmp_bytea,
-- 2. call this function
create or replace function swh_content_license_missing()
    returns setof sha1
    language plpgsql
as $$
begin
    return query
	(select id::sha1 from tmp_bytea as tmp
	 where not exists
	     (select 1 from content_license as c where c.id = tmp.id));
    return;
end
$$;

comment on function swh_content_license_missing() IS 'Filter missing content licenses';

-- add tmp_content_license entries to content_license, overwriting
-- duplicates if conflict_update is true, skipping duplicates otherwise.
--
-- If filtering duplicates is in order, the call to
-- swh_content_license_missing must take place before calling this
-- function.
--
-- operates in bulk: 0. swh_mktemp(content_license), 1. COPY to
-- tmp_content_license, 2. call this function
create or replace function swh_content_license_add(conflict_update boolean)
    returns void
    language plpgsql
as $$
begin
    if conflict_update then
        insert into content_license (id, licenses)
        select tcl.id, array(select id from license where name = ANY(tcl.licenses)) as licenses
    	from tmp_content_license tcl
            on conflict(id)
                do update set licenses = excluded.licenses;

    else
        insert into content_license (id, licenses)
        select tcl.id, array(select id from license where name = ANY(tcl.licenses)) as licenses
    	from tmp_content_license tcl
            on conflict do nothing;
    end if;
    return;
end
$$;

comment on function swh_content_license_add(boolean) IS 'Add new content licenses';

create type content_license_signature as (
  id      sha1,
  licenses bytea[]
);

-- Retrieve list of content license from the temporary table.
--
-- operates in bulk: 0. mktemp(tmp_bytea), 1. COPY to tmp_bytea,
-- 2. call this function
create or replace function swh_content_license_get()
    returns setof content_license_signature
    language plpgsql
as $$
begin
    return query
        select id::sha1, array(select name from license where id = ANY(cl.licenses)) as licenses
        from tmp_bytea
        inner join content_license cl using(id);
    return;
end
$$;

comment on function swh_content_license_get() IS 'List content licenses';
